services:
  bio-revision:
    build: .
    container_name: bio-revision
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=8000
      - HOSTNAME=0.0.0.0
      # Application-specific environment variables
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - R2_ACCOUNT_ID=${R2_ACCOUNT_ID}
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_BUCKET_NAME=${R2_BUCKET_NAME}
      - R2_PUBLIC_URL=${R2_PUBLIC_URL}
      - REDIS_URL=redis://redis:6379
      - MAX_PDF_SIZE_MB=${MAX_PDF_SIZE_MB}
    volumes:
      - quiz_data:/app/data
    networks:
      - caddy_net
      - backend_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "caddy=quiz.localhost"
      - "caddy.reverse_proxy={{upstreams 8000}}"

  redis:
    image: redis:7-alpine
    container_name: bio-revision-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - backend_net
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    command: [
      "redis-server",
      "--maxmemory", "400mb",
      "--maxmemory-policy", "noeviction",
      "--save", "900", "1",
      "--save", "300", "10", 
      "--save", "60", "10000"
    ]

volumes:
  quiz_data:
    driver: local
  redis_data:
    driver: local

networks:
  caddy_net:
    external: true
  backend_net:
    driver: bridge
